// <auto-generated />
using AspireStarterDb.ApiDbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireStarterDb.ApiDbService.Migrations
{
    [DbContext(typeof(TodosDbContext))]
    partial class TodosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireStarterDb.ApiDbModel.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = false,
                            Title = "Walk the dog"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Title = "Do the dishes"
                        },
                        new
                        {
                            Id = 3,
                            IsComplete = true,
                            Title = "Do the laundry"
                        },
                        new
                        {
                            Id = 4,
                            IsComplete = false,
                            Title = "Clean the bathroom"
                        },
                        new
                        {
                            Id = 5,
                            IsComplete = true,
                            Title = "Clean the car"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
